status bar

diff --git a/record-toggle b/record-toggle
--- a/record-toggle
+++ b/record-toggle
@@ -1,6 +1,16 @@
 #!/bin/env bash
 
-cmd="restatus 12 dwmblocks"
+# Source utils
+[[ -f "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils" ]] && source "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils"
+
+# Ensure ffmpeg is installed
+if ! command -v ffmpeg &> /dev/null; then
+    echo "Error: ffmpeg not found. Please install it first."
+    exit 1
+fi
+
+status="${STATUSBAR:-dwmblocks}"
+cmd="restatus 12 $status"
 
 function record() {
     # Create output directory
diff --git a/songctrl b/songctrl
--- a/songctrl
+++ b/songctrl
@@ -2,10 +2,20 @@
 
 set -euo pipefail
 
+# Source utils
+[[ -f "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils" ]] && source "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils"
+
+# playerctl found?
+if ! command -v playerctl &>/dev/null; then
+    echo "Error: playerctl not found. Please install it first."
+    exit 1
+fi
+
 opt="${1:-}"
 player="${2:-Supersonic}"
 cutpoint="${3:-0}"
-cmd="restatus 14 dwmblocks"
+status="${STATUSBAR:-dwmblocks}"
+cmd="restatus 14 $status"
 
 function song_togglepause() {
     playerctl play-pause --player="$player"
