help for the ones i thought needed

diff --git a/songctrl b/songctrl
--- a/songctrl
+++ b/songctrl
@@ -1,26 +1,25 @@
 #!/bin/env bash
 
+set -euo pipefail
+
+opt="${1:-}"
 player="${2:-Supersonic}"
 cutpoint="${3:-0}"
-parent_cmd=$(ps -o comm= -p $PPID)
-
-if [[ "$parent_cmd" == "slstatus" ]]; then
-    COMMAND="pkill -RTMIN+13 slstatus"
-fi
+cmd="pkill -RTMIN+13 slstatus"
 
 song_togglepause(){
     playerctl play-pause --player="$player"
-    [[ -n "$COMMAND" ]] && $COMMAND
+    $cmd
 }
 
 song_skip(){
     playerctl next --player="$player"
-    [[ -n "$COMMAND" ]] && $COMMAND
+    $cmd
 }
 
 song_previous(){
     playerctl previous --player="$player"
-    [[ -n "$COMMAND" ]] && $COMMAND
+    $cmd
 }
 
 song_title(){
@@ -44,8 +43,7 @@ song_title(){
     else
         echo "Not Playing/Paused"
     fi
-
-    [[ -n "$COMMAND" ]] && $COMMAND
+    $cmd
 }
 
 song_state(){
@@ -68,10 +66,24 @@ song_state(){
             fi
             ;;
     esac
-    [[ -n "$COMMAND" ]] && $COMMAND
+    $cmd
 }
 
-case "$1" in
+function help_menu() {
+    cat <<EOF
+Usage: $(basename "$0") [OPTION]
+
+Options:
+    --help, -h              Show this help message
+    --togglepause, -tp      Toggle pause
+    --skip, -s              Skip song
+    --previous, -p          Previous song
+    --songtitle, -st        Show song title
+    --songstate, -ss        Show song state
+EOF
+}
+
+case "$opt" in
     --togglepause|-tp)
         song_togglepause ;;
     --skip|-s)
@@ -82,6 +94,10 @@ case "$1" in
         song_title ;;
     --songstate|-ss)
         song_state ;;
+    --help|-h)
+        help_menu ;;
     *)
-        echo "Usage: $0 [--togglepause|-tp | --skip|-s | --previous|-p | --songtitle|-st | --songstate|-ss] [PLAYER] [CUTPOINT]" ;;
+        echo "Error: '${opt:- }' Invalid option."
+        help_menu
+        exit 1 ;;
 esac
diff --git a/sysstats b/sysstats
--- a/sysstats
+++ b/sysstats
@@ -1,5 +1,9 @@
 #!/bin/env bash
 
+set -euo pipefail
+
+opt="${1:-}"
+
 ttime() {
     date +"󰥔  %I:%M %p"
 }
@@ -55,7 +59,25 @@ all_stats() {
     echo "$(disk_usage) | $(memory_usage) | $(cpu_load) | $(wifi_status) | $(tail_status) | $(ddate) | $(ttime)"
 }
 
-case "$1" in
+function help_menu() {
+    cat <<EOF
+  Usage: $(basename "$0") [OPTION]
+
+  Options:
+    -h, --help  Show this help message
+    cpu         Display CPU load
+    mem         Display memory usage
+    disk        Display disk usage
+    wifi        Display WiFi connection status
+    tail        Display tailscale connection status
+    date        Display date
+    time        Display time
+    date_time   Display date and time
+    all         Display all stats
+EOF
+}
+
+case "$opt" in
     cpu)
         cpu_load
         ;;
@@ -83,7 +105,12 @@ case "$1" in
     all)
         all_stats
         ;;
+    --help|-h)
+        help_menu
+        ;;
     *)
-        echo "Usage: $0 {cpu|disk|mem|wifi|tail|date|time|date_time|all}"
+        echo "Error: Unknown argument '${opt:- }'."
+        help_menu
+        exit 1
         ;;
 esac
diff --git a/volumectrl b/volumectrl
--- a/volumectrl
+++ b/volumectrl
@@ -1,28 +1,29 @@
 #!/bin/env bash
 
+set -euo pipefail
+
 # Ensure pamixer is installed
 if ! command -v pamixer &> /dev/null; then
     echo "Error: pamixer is not installed."
     exit 1
 fi
 
-# Validate volume increment/decrement value
-if [[ "$2" =~ ^[0-9]+$ ]]; then
-    num="$2"
-else
-    num=5  # Default volume step if not provided or invalid
-fi
+opt="${1:-}"
+num="${2:-5}"
 
 volume_inc() {
     pamixer -i "$num"
+    pkill -RTMIN+16 slstatus
 }
 
 volume_dec() {
     pamixer -d "$num"
+    pkill -RTMIN+16 slstatus
 }
 
 volume_togglemute() {
     pamixer --toggle-mute
+    pkill -RTMIN+16 slstatus
 }
 
 volume_vol() {
@@ -45,22 +46,34 @@ volume_vol() {
     fi
 }
 
+function help_menu() {
+    cat <<EOF
+Usage: $(basename "$0") [OPTION]
+
+Options:
+    --help, -h           Show this help menu
+    --togglemute, -tm    Toggle mute
+    --inc, -i            Increase volume by \${num}
+    --dec, -d            Decrease volume by \${num}
+    --printvol, -pv      Print current volume
+EOF
+}
+
 case "$1" in
-    --togglemute)
+    --togglemute|-tm)
         volume_togglemute
-        pkill -RTMIN+16 slstatus
         ;;
-    --inc)
+    --inc|-i)
         volume_inc
-        pkill -RTMIN+16 slstatus
         ;;
-    --dec)
+    --dec|-d)
         volume_dec
-        pkill -RTMIN+16 slstatus
         ;;
-    --printvol) volume_vol ;;
+    --printvol|-pv) volume_vol ;;
+    --help|-h) help_menu ;;
     *)
-        echo "Error: Unknown argument '$1'. Use --togglemute, --inc, --dec, or --printvol."
+        echo "Error: '${opt:- }' Invalid option."
+        help_menu
         exit 1
         ;;
 esac
diff --git a/xwall b/xwall
--- a/xwall
+++ b/xwall
@@ -1,8 +1,14 @@
 #!/bin/env bash
 
+set -euo pipefail
+
+opt="${1:-}"
+dir="${2:-}"
+time="${3:-900}"
+
 function timexwalr() {
-    local WALLPAPER_DIR="$1"
-    local INTERVAL="${2:-900}"
+    local WALLPAPER_DIR="$dir"
+    local INTERVAL="$time"
 
     # Ensure directory argument
     if [[ -z "$WALLPAPER_DIR" ]]; then
@@ -39,13 +45,13 @@ function timexwalr() {
 }
 
 function xwalr() {
+    local WALLPAPER_DIR="$dir"
+
     # Ensure a directory argument is provided
-    if [[ -z "$1" ]]; then
+    if [[ -z "$WALLPAPER_DIR" ]]; then
         echo "Error: $0: No wallpaper directory provided."
         exit 1
     fi
-
-    WALLPAPER_DIR="$1"
 
     # Check if the directory exists
     if [[ ! -d "$WALLPAPER_DIR" ]]; then
@@ -54,11 +60,11 @@ function xwalr() {
     fi
 
     # Get all connected monitors
-    MONITORS=($(xrandr | grep " connected" | cut -d ' ' -f1))
+    local MONITORS=($(xrandr | grep " connected" | cut -d ' ' -f1))
 
     # For each monitor, set a random wallpaper
     for monitor in "${MONITORS[@]}"; do
-        wp=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.gif' \) | shuf -n 1)
+        local wp=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.gif' \) | shuf -n 1)
         if [[ -n "$wp" ]]; then
             xwallpaper --output "$monitor" --stretch "$wp"
             echo "Wallpaper set on $monitor to $wp"
@@ -68,16 +74,31 @@ function xwalr() {
     done
 }
 
+function help_menu() {
+    cat <<EOF
+Usage: $(basename "$0") [OPTION]
+
+Options:
+  -h, --help                       Show this help message
+  timexwalr \${dir} \${time}       Change wallpaper every INTERVAL seconds randomly, on all connected displays.
+  xwalr \${dir}                    Set a random wallpaper on all connected displays.
+EOF
+}
+
 # Main program
-case "$1" in
+case "$opt" in
     timexwalr)
-        timexwalr "$2" "$3"
+        timexwalr "${dir}" "${time}"
         ;;
     xwalr)
-        xwalr "$2"
+        xwalr "${dir}"
+        ;;
+    --help|-h)
+        help_menu
         ;;
     *)
-        echo "Usage: $0 {timexwalr|xwalr} [wallpaper_directory] [change_interval]"
+        echo "Error: '${opt:- }' Invalid option."
+        help_menu
         exit 1
         ;;
 esac
diff --git a/ytdl b/ytdl
--- a/ytdl
+++ b/ytdl
@@ -2,37 +2,53 @@
 
 set -euo pipefail
 
-url="$1"
-type="$2"
+opt="$1"
+url="$2"
 output_folder="$HOME/Downloads"
 
 # Validate input
-if [[ -z "$url" || -z "$type" ]]; then
+if [[ -z "$opt" || -z "$url" ]]; then
     echo "Usage: get_youtube_content <url> <type: aud|vid|bth>"
-    return 1
+    exit 1
 fi
 
 # Check if yt-dlp is installed
 if ! command -v yt-dlp &>/dev/null; then
     echo "yt-dlp is not installed. Please install yt-dlp and try again."
-    return 1
+    exit 1
 fi
 
-case "$type" in
+function help_menu() {
+    cat <<EOF
+Usage: $(basename "$0") [OPTION]
+
+Options:
+  -h, --help        Show this help message
+  aud               Download audio only
+  vid               Download video only
+  bth               Download both audio and video
+EOF
+}
+
+case "$opt" in
     aud)
-        yt-dlp -x --audio-format mp3 --embed-thumbnail --add-metadata --audio-quality 0 "$url" -o "$output_folder/%(title)s.%(ext)s"
+        yt-dlp -x --audio-format mp3 --embed-thumbnail --add-metadata --audio-quality 0 "$opt" -o "$output_folder/%(title)s.%(ext)s"
         echo "Audio download completed. File saved in $output_folder."
         ;;
     vid)
-        yt-dlp -f "bestvideo" --merge-output-format mp4 --embed-thumbnail --add-metadata "$url" -o "$output_folder/%(title)s.%(ext)s"
+        yt-dlp -f "bestvideo" --merge-output-format mp4 --embed-thumbnail --add-metadata "$opt" -o "$output_folder/%(title)s.%(ext)s"
         echo "Video download completed. File saved in $output_folder."
         ;;
     bth)
-        yt-dlp -f "bestvideo+bestaudio" --merge-output-format mp4 --embed-thumbnail --add-metadata "$url" -o "$output_folder/%(title)s.%(ext)s"
+        yt-dlp -f "bestvideo+bestaudio" --merge-output-format mp4 --embed-thumbnail --add-metadata "$opt" -o "$output_folder/%(title)s.%(ext)s"
         echo "Combined audio and video download completed as an MP4. File saved in $output_folder."
         ;;
+    --help|-h)
+        help_menu
+        ;;
     *)
-        echo "Invalid type specified. Use aud, vid, or bth."
-        return 1
+        echo "Error: '${opt:- }' Invalid option."
+        help_menu
+        exit 1
         ;;
 esac
